name: Build and Run Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t debian-iproute2 .

      - name: Run Docker container
        run: docker run --name server-container debian-iproute2

      - name: Copy result.txt from Docker container to artifact
        run: docker cp server-container:/app/result.txt result.txt

      - name: Create artifact
        run: tar -czvf artifact.tar.gz result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact.tar.gz
